# Generated by Django 5.2.5 on 2026-02-16 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва страви')),
                ('available', models.BooleanField(default=True, verbose_name='Доступність страви')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис страви')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Інгредієнти')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Зображення страви')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна страви')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main.category', verbose_name='Категорія страви')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я замовника")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон замовника')),
                ('adress', models.CharField(max_length=255, verbose_name='Адреса доставки')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('online', 'Онлайн-оплата')], max_length=50, verbose_name='Спосіб оплати')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Загальна ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Коментарі до замовлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_with_dish', to='main.dish', verbose_name='Страва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes_in_order', to='main.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Страва в замовленні',
                'verbose_name_plural': 'Страви в замовленнях',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до страви')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відгуку')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.dish', verbose_name='Страва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
